from sqlalchemy import Column, Integer, String, DateTime, Text, JSON, Float, UniqueConstraint
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.types import TypeDecorator
from datetime import datetime
from app.models import Base


class TSVectorType(TypeDecorator):
    """Custom type that uses TSVECTOR for PostgreSQL and Text for SQLite"""
    impl = Text
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == 'postgresql':
            return dialect.type_descriptor(TSVECTOR())
        else:
            return dialect.type_descriptor(Text())


class Job(Base):
    __tablename__ = "jobs"
    __table_args__ = (
        UniqueConstraint('source', 'source_id', name='uq_job_source_source_id'),
    )

    id = Column(Integer, primary_key=True, index=True)

    # Source info
    source = Column(String, nullable=False, index=True)  # remoteok, weworkremotely, etc.
    source_id = Column(String, nullable=False, index=True)
    url = Column(String, nullable=False)

    # Job details
    title = Column(String, nullable=False, index=True)
    company = Column(String, nullable=False, index=True)
    description = Column(Text, nullable=False)

    # Salary
    salary_min = Column(Integer, nullable=True)
    salary_max = Column(Integer, nullable=True)
    salary_currency = Column(String, default="USD")

    # Location and remote
    location = Column(String, default="Remote")
    remote_type = Column(String, default="full")  # full, partial, none

    # Job type
    job_type = Column(String, default="permanent")  # permanent, contract, part-time

    # Tags/skills
    tags = Column(JSON, default=list)

    # Employment eligibility
    eligible_regions = Column(JSON, default=lambda: ["Worldwide"])  # ["US", "EU", "Worldwide", etc.]
    visa_sponsorship = Column(Integer, nullable=True)  # NULL = not specified, 0 = no, 1 = yes

    # Timestamps
    posted_at = Column(DateTime, nullable=True)
    scraped_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Raw data from source
    raw_data = Column(JSON, nullable=True)

    # Full-text search vector (auto-generated by DB trigger in PostgreSQL, text in SQLite)
    search_vector = Column(TSVectorType, nullable=True)

    def __repr__(self):
        return f"<Job(id={self.id}, title='{self.title}', company='{self.company}')>"
