output "database_url" {
  description = "PostgreSQL connection string"
  value       = "postgresql://${neon_project.main.database_user}:${neon_project.main.database_password}@${neon_project.main.database_host}/${neon_database.main.name}?sslmode=require"
  sensitive   = true
}

output "database_host" {
  description = "PostgreSQL host"
  value       = neon_project.main.database_host
}

output "redis_url" {
  description = "Redis connection string"
  value       = "rediss://:${upstash_redis_database.main.password}@${upstash_redis_database.main.endpoint}:${upstash_redis_database.main.port}"
  sensitive   = true
}

output "redis_endpoint" {
  description = "Redis endpoint"
  value       = upstash_redis_database.main.endpoint
}

output "backend_url" {
  description = "Backend API URL"
  value       = "https://${fly_app.backend.name}.fly.dev"
}

output "backend_app_name" {
  description = "Fly.io app name for deployments"
  value       = fly_app.backend.name
}

output "frontend_url" {
  description = "Frontend URL"
  value       = "https://${vercel_project_domain.frontend.domain}"
}

output "vercel_project_id" {
  description = "Vercel project ID"
  value       = vercel_project.frontend.id
}

# Helper output for .env file
output "env_file_content" {
  description = "Content for .env file (DO NOT COMMIT)"
  sensitive   = true
  value       = <<-EOT
    # Generated by Terraform - DO NOT COMMIT
    DATABASE_URL=postgresql://${neon_project.main.database_user}:${neon_project.main.database_password}@${neon_project.main.database_host}/${neon_database.main.name}?sslmode=require
    REDIS_URL=rediss://:${upstash_redis_database.main.password}@${upstash_redis_database.main.endpoint}:${upstash_redis_database.main.port}
    ANTHROPIC_API_KEY=${var.anthropic_api_key}
    JWT_SECRET=${var.jwt_secret}
    ENVIRONMENT=${var.environment}
  EOT
}
