# =============================================================================
# Railway Outputs
# =============================================================================

output "railway_project_id" {
  description = "Railway project ID"
  value       = railway_project.main.id
}

output "railway_project_name" {
  description = "Railway project name"
  value       = railway_project.main.name
}

# =============================================================================
# Generated Secrets
# =============================================================================

output "generated_postgres_password" {
  description = "Auto-generated PostgreSQL password (if not provided)"
  value       = local.postgres_password
  sensitive   = true
}

output "generated_jwt_secret" {
  description = "Auto-generated JWT secret (if not provided)"
  value       = local.jwt_secret
  sensitive   = true
}

# =============================================================================
# Database Outputs
# =============================================================================

output "database_url" {
  description = "PostgreSQL connection string for backend"
  value       = railway_variable.backend_database_url.value
  sensitive   = true
}

output "postgres_service_id" {
  description = "Railway PostgreSQL service ID"
  value       = railway_service.postgres.id
}

# =============================================================================
# Redis Outputs
# =============================================================================

output "redis_url" {
  description = "Redis connection string for backend"
  value       = railway_variable.backend_redis_url.value
  sensitive   = true
}

output "redis_service_id" {
  description = "Railway Redis service ID"
  value       = railway_service.redis.id
}

# =============================================================================
# Backend Outputs
# =============================================================================

output "backend_url" {
  description = "Backend API URL (Railway domain)"
  value       = "https://${railway_service.backend.domain}"
}

output "backend_service_id" {
  description = "Railway backend service ID"
  value       = railway_service.backend.id
}

# =============================================================================
# Frontend Outputs
# =============================================================================

output "frontend_url" {
  description = "Frontend URL (Vercel domain)"
  value       = "https://${vercel_project_domain.frontend.domain}"
}

output "vercel_project_id" {
  description = "Vercel project ID"
  value       = vercel_project.frontend.id
}

# =============================================================================
# Environment File Helper
# =============================================================================

output "env_file_content" {
  description = "Content for .env file (DO NOT COMMIT THIS)"
  sensitive   = true
  value       = <<-EOT
    # Generated by Terraform - DO NOT COMMIT
    # Copy this to your .env file for local development

    # Environment
    ENVIRONMENT=${var.environment}
    LOG_LEVEL=${var.environment == "production" ? "INFO" : "DEBUG"}

    # Database (use Railway's internal connection for production)
    DATABASE_URL=${railway_variable.backend_database_url.value}

    # Redis (use Railway's internal connection for production)
    REDIS_URL=${railway_variable.backend_redis_url.value}

    # Anthropic API
    ANTHROPIC_API_KEY=${var.anthropic_api_key}

    # Auth
    JWT_SECRET=${local.jwt_secret}
    JWT_ALGORITHM=HS256
    JWT_EXPIRE_MINUTES=10080
  EOT
}

# =============================================================================
# Deployment Info
# =============================================================================

output "deployment_info" {
  description = "Summary of deployed infrastructure"
  value = {
    project_name     = railway_project.main.name
    backend_url      = "https://${railway_service.backend.domain}"
    frontend_url     = "https://${vercel_project_domain.frontend.domain}"
    database_service = railway_service.postgres.name
    redis_service    = railway_service.redis.name
    environment      = var.environment
  }
}
