"""add employment eligibility fields to jobs

Revision ID: 05069ca43c64
Revises: 51a810a2b2d8
Create Date: 2025-12-19 19:46:11.201351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05069ca43c64'
down_revision: Union[str, None] = '51a810a2b2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_allowed_emails_email', table_name='allowed_emails')
    op.drop_constraint('uq_allowed_emails_email', 'allowed_emails', type_='unique')
    op.create_index(op.f('ix_allowed_emails_email'), 'allowed_emails', ['email'], unique=True)
    op.create_index(op.f('ix_allowed_emails_id'), 'allowed_emails', ['id'], unique=False)
    op.add_column('jobs', sa.Column('eligible_regions', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('visa_sponsorship', sa.Integer(), nullable=True))
    op.drop_index('idx_jobs_job_type_scraped_at', table_name='jobs')
    op.drop_index('idx_jobs_remote_type_scraped_at', table_name='jobs')
    op.drop_index('idx_jobs_scraped_at', table_name='jobs')
    op.drop_index('idx_jobs_search_vector', table_name='jobs', postgresql_using='gin')
    op.drop_index('idx_jobs_source_scraped_at', table_name='jobs')
    op.drop_constraint('uq_jobs_source_source_id', 'jobs', type_='unique')
    op.create_unique_constraint('uq_job_source_source_id', 'jobs', ['source', 'source_id'])
    op.drop_index('idx_matches_user_score', table_name='matches')
    op.drop_index('idx_matches_user_status', table_name='matches')
    op.drop_index('idx_matches_user_status_score', table_name='matches')
    op.alter_column('scrape_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scrape_logs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('skill_analysis', 'analysis_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('skill_analysis_user_id_key', 'skill_analysis', type_='unique')
    op.drop_index('ix_skill_analysis_user_id', table_name='skill_analysis')
    op.create_index(op.f('ix_skill_analysis_user_id'), 'skill_analysis', ['user_id'], unique=True)
    op.drop_index('idx_user_jobs_created_at', table_name='user_jobs')
    op.drop_index('idx_user_jobs_user_id', table_name='user_jobs')
    op.create_index(op.f('ix_user_jobs_id'), 'user_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_user_jobs_user_id'), 'user_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_jobs_user_id'), table_name='user_jobs')
    op.drop_index(op.f('ix_user_jobs_id'), table_name='user_jobs')
    op.create_index('idx_user_jobs_user_id', 'user_jobs', ['user_id'], unique=False)
    op.create_index('idx_user_jobs_created_at', 'user_jobs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_skill_analysis_user_id'), table_name='skill_analysis')
    op.create_index('ix_skill_analysis_user_id', 'skill_analysis', ['user_id'], unique=False)
    op.create_unique_constraint('skill_analysis_user_id_key', 'skill_analysis', ['user_id'])
    op.alter_column('skill_analysis', 'analysis_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scrape_logs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('scrape_logs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_matches_user_status_score', 'matches', ['user_id', 'status', 'score'], unique=False)
    op.create_index('idx_matches_user_status', 'matches', ['user_id', 'status'], unique=False)
    op.create_index('idx_matches_user_score', 'matches', ['user_id', 'score'], unique=False)
    op.drop_constraint('uq_job_source_source_id', 'jobs', type_='unique')
    op.create_unique_constraint('uq_jobs_source_source_id', 'jobs', ['source', 'source_id'])
    op.create_index('idx_jobs_source_scraped_at', 'jobs', ['source', 'scraped_at'], unique=False)
    op.create_index('idx_jobs_search_vector', 'jobs', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_jobs_scraped_at', 'jobs', ['scraped_at'], unique=False)
    op.create_index('idx_jobs_remote_type_scraped_at', 'jobs', ['remote_type', 'scraped_at'], unique=False)
    op.create_index('idx_jobs_job_type_scraped_at', 'jobs', ['job_type', 'scraped_at'], unique=False)
    op.drop_column('jobs', 'visa_sponsorship')
    op.drop_column('jobs', 'eligible_regions')
    op.drop_index(op.f('ix_allowed_emails_id'), table_name='allowed_emails')
    op.drop_index(op.f('ix_allowed_emails_email'), table_name='allowed_emails')
    op.create_unique_constraint('uq_allowed_emails_email', 'allowed_emails', ['email'])
    op.create_index('idx_allowed_emails_email', 'allowed_emails', ['email'], unique=False)
    # ### end Alembic commands ###
